// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i wallet-app/internal/api/handler/create_api_1_wallet.Service -o service_mock.go -n ServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"
	"wallet-app/internal/domain/wallet/repository/mapper_objects"

	"github.com/gojuno/minimock/v3"
)

// ServiceMock implements mm_create_api_1_wallet.Service
type ServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateWallet          func(ctx context.Context, initialBalance int64) (wp1 *mapper_objects.Wallet, err error)
	funcCreateWalletOrigin    string
	inspectFuncCreateWallet   func(ctx context.Context, initialBalance int64)
	afterCreateWalletCounter  uint64
	beforeCreateWalletCounter uint64
	CreateWalletMock          mServiceMockCreateWallet
}

// NewServiceMock returns a mock for mm_create_api_1_wallet.Service
func NewServiceMock(t minimock.Tester) *ServiceMock {
	m := &ServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateWalletMock = mServiceMockCreateWallet{mock: m}
	m.CreateWalletMock.callArgs = []*ServiceMockCreateWalletParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mServiceMockCreateWallet struct {
	optional           bool
	mock               *ServiceMock
	defaultExpectation *ServiceMockCreateWalletExpectation
	expectations       []*ServiceMockCreateWalletExpectation

	callArgs []*ServiceMockCreateWalletParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ServiceMockCreateWalletExpectation specifies expectation struct of the Service.CreateWallet
type ServiceMockCreateWalletExpectation struct {
	mock               *ServiceMock
	params             *ServiceMockCreateWalletParams
	paramPtrs          *ServiceMockCreateWalletParamPtrs
	expectationOrigins ServiceMockCreateWalletExpectationOrigins
	results            *ServiceMockCreateWalletResults
	returnOrigin       string
	Counter            uint64
}

// ServiceMockCreateWalletParams contains parameters of the Service.CreateWallet
type ServiceMockCreateWalletParams struct {
	ctx            context.Context
	initialBalance int64
}

// ServiceMockCreateWalletParamPtrs contains pointers to parameters of the Service.CreateWallet
type ServiceMockCreateWalletParamPtrs struct {
	ctx            *context.Context
	initialBalance *int64
}

// ServiceMockCreateWalletResults contains results of the Service.CreateWallet
type ServiceMockCreateWalletResults struct {
	wp1 *mapper_objects.Wallet
	err error
}

// ServiceMockCreateWalletOrigins contains origins of expectations of the Service.CreateWallet
type ServiceMockCreateWalletExpectationOrigins struct {
	origin               string
	originCtx            string
	originInitialBalance string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateWallet *mServiceMockCreateWallet) Optional() *mServiceMockCreateWallet {
	mmCreateWallet.optional = true
	return mmCreateWallet
}

// Expect sets up expected params for Service.CreateWallet
func (mmCreateWallet *mServiceMockCreateWallet) Expect(ctx context.Context, initialBalance int64) *mServiceMockCreateWallet {
	if mmCreateWallet.mock.funcCreateWallet != nil {
		mmCreateWallet.mock.t.Fatalf("ServiceMock.CreateWallet mock is already set by Set")
	}

	if mmCreateWallet.defaultExpectation == nil {
		mmCreateWallet.defaultExpectation = &ServiceMockCreateWalletExpectation{}
	}

	if mmCreateWallet.defaultExpectation.paramPtrs != nil {
		mmCreateWallet.mock.t.Fatalf("ServiceMock.CreateWallet mock is already set by ExpectParams functions")
	}

	mmCreateWallet.defaultExpectation.params = &ServiceMockCreateWalletParams{ctx, initialBalance}
	mmCreateWallet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateWallet.expectations {
		if minimock.Equal(e.params, mmCreateWallet.defaultExpectation.params) {
			mmCreateWallet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateWallet.defaultExpectation.params)
		}
	}

	return mmCreateWallet
}

// ExpectCtxParam1 sets up expected param ctx for Service.CreateWallet
func (mmCreateWallet *mServiceMockCreateWallet) ExpectCtxParam1(ctx context.Context) *mServiceMockCreateWallet {
	if mmCreateWallet.mock.funcCreateWallet != nil {
		mmCreateWallet.mock.t.Fatalf("ServiceMock.CreateWallet mock is already set by Set")
	}

	if mmCreateWallet.defaultExpectation == nil {
		mmCreateWallet.defaultExpectation = &ServiceMockCreateWalletExpectation{}
	}

	if mmCreateWallet.defaultExpectation.params != nil {
		mmCreateWallet.mock.t.Fatalf("ServiceMock.CreateWallet mock is already set by Expect")
	}

	if mmCreateWallet.defaultExpectation.paramPtrs == nil {
		mmCreateWallet.defaultExpectation.paramPtrs = &ServiceMockCreateWalletParamPtrs{}
	}
	mmCreateWallet.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateWallet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateWallet
}

// ExpectInitialBalanceParam2 sets up expected param initialBalance for Service.CreateWallet
func (mmCreateWallet *mServiceMockCreateWallet) ExpectInitialBalanceParam2(initialBalance int64) *mServiceMockCreateWallet {
	if mmCreateWallet.mock.funcCreateWallet != nil {
		mmCreateWallet.mock.t.Fatalf("ServiceMock.CreateWallet mock is already set by Set")
	}

	if mmCreateWallet.defaultExpectation == nil {
		mmCreateWallet.defaultExpectation = &ServiceMockCreateWalletExpectation{}
	}

	if mmCreateWallet.defaultExpectation.params != nil {
		mmCreateWallet.mock.t.Fatalf("ServiceMock.CreateWallet mock is already set by Expect")
	}

	if mmCreateWallet.defaultExpectation.paramPtrs == nil {
		mmCreateWallet.defaultExpectation.paramPtrs = &ServiceMockCreateWalletParamPtrs{}
	}
	mmCreateWallet.defaultExpectation.paramPtrs.initialBalance = &initialBalance
	mmCreateWallet.defaultExpectation.expectationOrigins.originInitialBalance = minimock.CallerInfo(1)

	return mmCreateWallet
}

// Inspect accepts an inspector function that has same arguments as the Service.CreateWallet
func (mmCreateWallet *mServiceMockCreateWallet) Inspect(f func(ctx context.Context, initialBalance int64)) *mServiceMockCreateWallet {
	if mmCreateWallet.mock.inspectFuncCreateWallet != nil {
		mmCreateWallet.mock.t.Fatalf("Inspect function is already set for ServiceMock.CreateWallet")
	}

	mmCreateWallet.mock.inspectFuncCreateWallet = f

	return mmCreateWallet
}

// Return sets up results that will be returned by Service.CreateWallet
func (mmCreateWallet *mServiceMockCreateWallet) Return(wp1 *mapper_objects.Wallet, err error) *ServiceMock {
	if mmCreateWallet.mock.funcCreateWallet != nil {
		mmCreateWallet.mock.t.Fatalf("ServiceMock.CreateWallet mock is already set by Set")
	}

	if mmCreateWallet.defaultExpectation == nil {
		mmCreateWallet.defaultExpectation = &ServiceMockCreateWalletExpectation{mock: mmCreateWallet.mock}
	}
	mmCreateWallet.defaultExpectation.results = &ServiceMockCreateWalletResults{wp1, err}
	mmCreateWallet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateWallet.mock
}

// Set uses given function f to mock the Service.CreateWallet method
func (mmCreateWallet *mServiceMockCreateWallet) Set(f func(ctx context.Context, initialBalance int64) (wp1 *mapper_objects.Wallet, err error)) *ServiceMock {
	if mmCreateWallet.defaultExpectation != nil {
		mmCreateWallet.mock.t.Fatalf("Default expectation is already set for the Service.CreateWallet method")
	}

	if len(mmCreateWallet.expectations) > 0 {
		mmCreateWallet.mock.t.Fatalf("Some expectations are already set for the Service.CreateWallet method")
	}

	mmCreateWallet.mock.funcCreateWallet = f
	mmCreateWallet.mock.funcCreateWalletOrigin = minimock.CallerInfo(1)
	return mmCreateWallet.mock
}

// When sets expectation for the Service.CreateWallet which will trigger the result defined by the following
// Then helper
func (mmCreateWallet *mServiceMockCreateWallet) When(ctx context.Context, initialBalance int64) *ServiceMockCreateWalletExpectation {
	if mmCreateWallet.mock.funcCreateWallet != nil {
		mmCreateWallet.mock.t.Fatalf("ServiceMock.CreateWallet mock is already set by Set")
	}

	expectation := &ServiceMockCreateWalletExpectation{
		mock:               mmCreateWallet.mock,
		params:             &ServiceMockCreateWalletParams{ctx, initialBalance},
		expectationOrigins: ServiceMockCreateWalletExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateWallet.expectations = append(mmCreateWallet.expectations, expectation)
	return expectation
}

// Then sets up Service.CreateWallet return parameters for the expectation previously defined by the When method
func (e *ServiceMockCreateWalletExpectation) Then(wp1 *mapper_objects.Wallet, err error) *ServiceMock {
	e.results = &ServiceMockCreateWalletResults{wp1, err}
	return e.mock
}

// Times sets number of times Service.CreateWallet should be invoked
func (mmCreateWallet *mServiceMockCreateWallet) Times(n uint64) *mServiceMockCreateWallet {
	if n == 0 {
		mmCreateWallet.mock.t.Fatalf("Times of ServiceMock.CreateWallet mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateWallet.expectedInvocations, n)
	mmCreateWallet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateWallet
}

func (mmCreateWallet *mServiceMockCreateWallet) invocationsDone() bool {
	if len(mmCreateWallet.expectations) == 0 && mmCreateWallet.defaultExpectation == nil && mmCreateWallet.mock.funcCreateWallet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateWallet.mock.afterCreateWalletCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateWallet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateWallet implements mm_create_api_1_wallet.Service
func (mmCreateWallet *ServiceMock) CreateWallet(ctx context.Context, initialBalance int64) (wp1 *mapper_objects.Wallet, err error) {
	mm_atomic.AddUint64(&mmCreateWallet.beforeCreateWalletCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateWallet.afterCreateWalletCounter, 1)

	mmCreateWallet.t.Helper()

	if mmCreateWallet.inspectFuncCreateWallet != nil {
		mmCreateWallet.inspectFuncCreateWallet(ctx, initialBalance)
	}

	mm_params := ServiceMockCreateWalletParams{ctx, initialBalance}

	// Record call args
	mmCreateWallet.CreateWalletMock.mutex.Lock()
	mmCreateWallet.CreateWalletMock.callArgs = append(mmCreateWallet.CreateWalletMock.callArgs, &mm_params)
	mmCreateWallet.CreateWalletMock.mutex.Unlock()

	for _, e := range mmCreateWallet.CreateWalletMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.wp1, e.results.err
		}
	}

	if mmCreateWallet.CreateWalletMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateWallet.CreateWalletMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateWallet.CreateWalletMock.defaultExpectation.params
		mm_want_ptrs := mmCreateWallet.CreateWalletMock.defaultExpectation.paramPtrs

		mm_got := ServiceMockCreateWalletParams{ctx, initialBalance}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateWallet.t.Errorf("ServiceMock.CreateWallet got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateWallet.CreateWalletMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.initialBalance != nil && !minimock.Equal(*mm_want_ptrs.initialBalance, mm_got.initialBalance) {
				mmCreateWallet.t.Errorf("ServiceMock.CreateWallet got unexpected parameter initialBalance, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateWallet.CreateWalletMock.defaultExpectation.expectationOrigins.originInitialBalance, *mm_want_ptrs.initialBalance, mm_got.initialBalance, minimock.Diff(*mm_want_ptrs.initialBalance, mm_got.initialBalance))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateWallet.t.Errorf("ServiceMock.CreateWallet got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateWallet.CreateWalletMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateWallet.CreateWalletMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateWallet.t.Fatal("No results are set for the ServiceMock.CreateWallet")
		}
		return (*mm_results).wp1, (*mm_results).err
	}
	if mmCreateWallet.funcCreateWallet != nil {
		return mmCreateWallet.funcCreateWallet(ctx, initialBalance)
	}
	mmCreateWallet.t.Fatalf("Unexpected call to ServiceMock.CreateWallet. %v %v", ctx, initialBalance)
	return
}

// CreateWalletAfterCounter returns a count of finished ServiceMock.CreateWallet invocations
func (mmCreateWallet *ServiceMock) CreateWalletAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateWallet.afterCreateWalletCounter)
}

// CreateWalletBeforeCounter returns a count of ServiceMock.CreateWallet invocations
func (mmCreateWallet *ServiceMock) CreateWalletBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateWallet.beforeCreateWalletCounter)
}

// Calls returns a list of arguments used in each call to ServiceMock.CreateWallet.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateWallet *mServiceMockCreateWallet) Calls() []*ServiceMockCreateWalletParams {
	mmCreateWallet.mutex.RLock()

	argCopy := make([]*ServiceMockCreateWalletParams, len(mmCreateWallet.callArgs))
	copy(argCopy, mmCreateWallet.callArgs)

	mmCreateWallet.mutex.RUnlock()

	return argCopy
}

// MinimockCreateWalletDone returns true if the count of the CreateWallet invocations corresponds
// the number of defined expectations
func (m *ServiceMock) MinimockCreateWalletDone() bool {
	if m.CreateWalletMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateWalletMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateWalletMock.invocationsDone()
}

// MinimockCreateWalletInspect logs each unmet expectation
func (m *ServiceMock) MinimockCreateWalletInspect() {
	for _, e := range m.CreateWalletMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ServiceMock.CreateWallet at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateWalletCounter := mm_atomic.LoadUint64(&m.afterCreateWalletCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateWalletMock.defaultExpectation != nil && afterCreateWalletCounter < 1 {
		if m.CreateWalletMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ServiceMock.CreateWallet at\n%s", m.CreateWalletMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ServiceMock.CreateWallet at\n%s with params: %#v", m.CreateWalletMock.defaultExpectation.expectationOrigins.origin, *m.CreateWalletMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateWallet != nil && afterCreateWalletCounter < 1 {
		m.t.Errorf("Expected call to ServiceMock.CreateWallet at\n%s", m.funcCreateWalletOrigin)
	}

	if !m.CreateWalletMock.invocationsDone() && afterCreateWalletCounter > 0 {
		m.t.Errorf("Expected %d calls to ServiceMock.CreateWallet at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateWalletMock.expectedInvocations), m.CreateWalletMock.expectedInvocationsOrigin, afterCreateWalletCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateWalletInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateWalletDone()
}
