// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i wallet-app/internal/api/handler/get_api_1_wallets.Service -o service_mock.go -n ServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"
	"wallet-app/internal/domain/wallet/repository/mapper_objects"

	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
)

// ServiceMock implements mm_get_api_1_wallets.Service
type ServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetWallet          func(ctx context.Context, id uuid.UUID) (wp1 *mapper_objects.Wallet, err error)
	funcGetWalletOrigin    string
	inspectFuncGetWallet   func(ctx context.Context, id uuid.UUID)
	afterGetWalletCounter  uint64
	beforeGetWalletCounter uint64
	GetWalletMock          mServiceMockGetWallet
}

// NewServiceMock returns a mock for mm_get_api_1_wallets.Service
func NewServiceMock(t minimock.Tester) *ServiceMock {
	m := &ServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetWalletMock = mServiceMockGetWallet{mock: m}
	m.GetWalletMock.callArgs = []*ServiceMockGetWalletParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mServiceMockGetWallet struct {
	optional           bool
	mock               *ServiceMock
	defaultExpectation *ServiceMockGetWalletExpectation
	expectations       []*ServiceMockGetWalletExpectation

	callArgs []*ServiceMockGetWalletParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ServiceMockGetWalletExpectation specifies expectation struct of the Service.GetWallet
type ServiceMockGetWalletExpectation struct {
	mock               *ServiceMock
	params             *ServiceMockGetWalletParams
	paramPtrs          *ServiceMockGetWalletParamPtrs
	expectationOrigins ServiceMockGetWalletExpectationOrigins
	results            *ServiceMockGetWalletResults
	returnOrigin       string
	Counter            uint64
}

// ServiceMockGetWalletParams contains parameters of the Service.GetWallet
type ServiceMockGetWalletParams struct {
	ctx context.Context
	id  uuid.UUID
}

// ServiceMockGetWalletParamPtrs contains pointers to parameters of the Service.GetWallet
type ServiceMockGetWalletParamPtrs struct {
	ctx *context.Context
	id  *uuid.UUID
}

// ServiceMockGetWalletResults contains results of the Service.GetWallet
type ServiceMockGetWalletResults struct {
	wp1 *mapper_objects.Wallet
	err error
}

// ServiceMockGetWalletOrigins contains origins of expectations of the Service.GetWallet
type ServiceMockGetWalletExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetWallet *mServiceMockGetWallet) Optional() *mServiceMockGetWallet {
	mmGetWallet.optional = true
	return mmGetWallet
}

// Expect sets up expected params for Service.GetWallet
func (mmGetWallet *mServiceMockGetWallet) Expect(ctx context.Context, id uuid.UUID) *mServiceMockGetWallet {
	if mmGetWallet.mock.funcGetWallet != nil {
		mmGetWallet.mock.t.Fatalf("ServiceMock.GetWallet mock is already set by Set")
	}

	if mmGetWallet.defaultExpectation == nil {
		mmGetWallet.defaultExpectation = &ServiceMockGetWalletExpectation{}
	}

	if mmGetWallet.defaultExpectation.paramPtrs != nil {
		mmGetWallet.mock.t.Fatalf("ServiceMock.GetWallet mock is already set by ExpectParams functions")
	}

	mmGetWallet.defaultExpectation.params = &ServiceMockGetWalletParams{ctx, id}
	mmGetWallet.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetWallet.expectations {
		if minimock.Equal(e.params, mmGetWallet.defaultExpectation.params) {
			mmGetWallet.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetWallet.defaultExpectation.params)
		}
	}

	return mmGetWallet
}

// ExpectCtxParam1 sets up expected param ctx for Service.GetWallet
func (mmGetWallet *mServiceMockGetWallet) ExpectCtxParam1(ctx context.Context) *mServiceMockGetWallet {
	if mmGetWallet.mock.funcGetWallet != nil {
		mmGetWallet.mock.t.Fatalf("ServiceMock.GetWallet mock is already set by Set")
	}

	if mmGetWallet.defaultExpectation == nil {
		mmGetWallet.defaultExpectation = &ServiceMockGetWalletExpectation{}
	}

	if mmGetWallet.defaultExpectation.params != nil {
		mmGetWallet.mock.t.Fatalf("ServiceMock.GetWallet mock is already set by Expect")
	}

	if mmGetWallet.defaultExpectation.paramPtrs == nil {
		mmGetWallet.defaultExpectation.paramPtrs = &ServiceMockGetWalletParamPtrs{}
	}
	mmGetWallet.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetWallet.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetWallet
}

// ExpectIdParam2 sets up expected param id for Service.GetWallet
func (mmGetWallet *mServiceMockGetWallet) ExpectIdParam2(id uuid.UUID) *mServiceMockGetWallet {
	if mmGetWallet.mock.funcGetWallet != nil {
		mmGetWallet.mock.t.Fatalf("ServiceMock.GetWallet mock is already set by Set")
	}

	if mmGetWallet.defaultExpectation == nil {
		mmGetWallet.defaultExpectation = &ServiceMockGetWalletExpectation{}
	}

	if mmGetWallet.defaultExpectation.params != nil {
		mmGetWallet.mock.t.Fatalf("ServiceMock.GetWallet mock is already set by Expect")
	}

	if mmGetWallet.defaultExpectation.paramPtrs == nil {
		mmGetWallet.defaultExpectation.paramPtrs = &ServiceMockGetWalletParamPtrs{}
	}
	mmGetWallet.defaultExpectation.paramPtrs.id = &id
	mmGetWallet.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetWallet
}

// Inspect accepts an inspector function that has same arguments as the Service.GetWallet
func (mmGetWallet *mServiceMockGetWallet) Inspect(f func(ctx context.Context, id uuid.UUID)) *mServiceMockGetWallet {
	if mmGetWallet.mock.inspectFuncGetWallet != nil {
		mmGetWallet.mock.t.Fatalf("Inspect function is already set for ServiceMock.GetWallet")
	}

	mmGetWallet.mock.inspectFuncGetWallet = f

	return mmGetWallet
}

// Return sets up results that will be returned by Service.GetWallet
func (mmGetWallet *mServiceMockGetWallet) Return(wp1 *mapper_objects.Wallet, err error) *ServiceMock {
	if mmGetWallet.mock.funcGetWallet != nil {
		mmGetWallet.mock.t.Fatalf("ServiceMock.GetWallet mock is already set by Set")
	}

	if mmGetWallet.defaultExpectation == nil {
		mmGetWallet.defaultExpectation = &ServiceMockGetWalletExpectation{mock: mmGetWallet.mock}
	}
	mmGetWallet.defaultExpectation.results = &ServiceMockGetWalletResults{wp1, err}
	mmGetWallet.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetWallet.mock
}

// Set uses given function f to mock the Service.GetWallet method
func (mmGetWallet *mServiceMockGetWallet) Set(f func(ctx context.Context, id uuid.UUID) (wp1 *mapper_objects.Wallet, err error)) *ServiceMock {
	if mmGetWallet.defaultExpectation != nil {
		mmGetWallet.mock.t.Fatalf("Default expectation is already set for the Service.GetWallet method")
	}

	if len(mmGetWallet.expectations) > 0 {
		mmGetWallet.mock.t.Fatalf("Some expectations are already set for the Service.GetWallet method")
	}

	mmGetWallet.mock.funcGetWallet = f
	mmGetWallet.mock.funcGetWalletOrigin = minimock.CallerInfo(1)
	return mmGetWallet.mock
}

// When sets expectation for the Service.GetWallet which will trigger the result defined by the following
// Then helper
func (mmGetWallet *mServiceMockGetWallet) When(ctx context.Context, id uuid.UUID) *ServiceMockGetWalletExpectation {
	if mmGetWallet.mock.funcGetWallet != nil {
		mmGetWallet.mock.t.Fatalf("ServiceMock.GetWallet mock is already set by Set")
	}

	expectation := &ServiceMockGetWalletExpectation{
		mock:               mmGetWallet.mock,
		params:             &ServiceMockGetWalletParams{ctx, id},
		expectationOrigins: ServiceMockGetWalletExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetWallet.expectations = append(mmGetWallet.expectations, expectation)
	return expectation
}

// Then sets up Service.GetWallet return parameters for the expectation previously defined by the When method
func (e *ServiceMockGetWalletExpectation) Then(wp1 *mapper_objects.Wallet, err error) *ServiceMock {
	e.results = &ServiceMockGetWalletResults{wp1, err}
	return e.mock
}

// Times sets number of times Service.GetWallet should be invoked
func (mmGetWallet *mServiceMockGetWallet) Times(n uint64) *mServiceMockGetWallet {
	if n == 0 {
		mmGetWallet.mock.t.Fatalf("Times of ServiceMock.GetWallet mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetWallet.expectedInvocations, n)
	mmGetWallet.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetWallet
}

func (mmGetWallet *mServiceMockGetWallet) invocationsDone() bool {
	if len(mmGetWallet.expectations) == 0 && mmGetWallet.defaultExpectation == nil && mmGetWallet.mock.funcGetWallet == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetWallet.mock.afterGetWalletCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetWallet.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetWallet implements mm_get_api_1_wallets.Service
func (mmGetWallet *ServiceMock) GetWallet(ctx context.Context, id uuid.UUID) (wp1 *mapper_objects.Wallet, err error) {
	mm_atomic.AddUint64(&mmGetWallet.beforeGetWalletCounter, 1)
	defer mm_atomic.AddUint64(&mmGetWallet.afterGetWalletCounter, 1)

	mmGetWallet.t.Helper()

	if mmGetWallet.inspectFuncGetWallet != nil {
		mmGetWallet.inspectFuncGetWallet(ctx, id)
	}

	mm_params := ServiceMockGetWalletParams{ctx, id}

	// Record call args
	mmGetWallet.GetWalletMock.mutex.Lock()
	mmGetWallet.GetWalletMock.callArgs = append(mmGetWallet.GetWalletMock.callArgs, &mm_params)
	mmGetWallet.GetWalletMock.mutex.Unlock()

	for _, e := range mmGetWallet.GetWalletMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.wp1, e.results.err
		}
	}

	if mmGetWallet.GetWalletMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetWallet.GetWalletMock.defaultExpectation.Counter, 1)
		mm_want := mmGetWallet.GetWalletMock.defaultExpectation.params
		mm_want_ptrs := mmGetWallet.GetWalletMock.defaultExpectation.paramPtrs

		mm_got := ServiceMockGetWalletParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetWallet.t.Errorf("ServiceMock.GetWallet got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetWallet.GetWalletMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetWallet.t.Errorf("ServiceMock.GetWallet got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetWallet.GetWalletMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetWallet.t.Errorf("ServiceMock.GetWallet got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetWallet.GetWalletMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetWallet.GetWalletMock.defaultExpectation.results
		if mm_results == nil {
			mmGetWallet.t.Fatal("No results are set for the ServiceMock.GetWallet")
		}
		return (*mm_results).wp1, (*mm_results).err
	}
	if mmGetWallet.funcGetWallet != nil {
		return mmGetWallet.funcGetWallet(ctx, id)
	}
	mmGetWallet.t.Fatalf("Unexpected call to ServiceMock.GetWallet. %v %v", ctx, id)
	return
}

// GetWalletAfterCounter returns a count of finished ServiceMock.GetWallet invocations
func (mmGetWallet *ServiceMock) GetWalletAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetWallet.afterGetWalletCounter)
}

// GetWalletBeforeCounter returns a count of ServiceMock.GetWallet invocations
func (mmGetWallet *ServiceMock) GetWalletBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetWallet.beforeGetWalletCounter)
}

// Calls returns a list of arguments used in each call to ServiceMock.GetWallet.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetWallet *mServiceMockGetWallet) Calls() []*ServiceMockGetWalletParams {
	mmGetWallet.mutex.RLock()

	argCopy := make([]*ServiceMockGetWalletParams, len(mmGetWallet.callArgs))
	copy(argCopy, mmGetWallet.callArgs)

	mmGetWallet.mutex.RUnlock()

	return argCopy
}

// MinimockGetWalletDone returns true if the count of the GetWallet invocations corresponds
// the number of defined expectations
func (m *ServiceMock) MinimockGetWalletDone() bool {
	if m.GetWalletMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetWalletMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetWalletMock.invocationsDone()
}

// MinimockGetWalletInspect logs each unmet expectation
func (m *ServiceMock) MinimockGetWalletInspect() {
	for _, e := range m.GetWalletMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ServiceMock.GetWallet at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetWalletCounter := mm_atomic.LoadUint64(&m.afterGetWalletCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetWalletMock.defaultExpectation != nil && afterGetWalletCounter < 1 {
		if m.GetWalletMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ServiceMock.GetWallet at\n%s", m.GetWalletMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ServiceMock.GetWallet at\n%s with params: %#v", m.GetWalletMock.defaultExpectation.expectationOrigins.origin, *m.GetWalletMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetWallet != nil && afterGetWalletCounter < 1 {
		m.t.Errorf("Expected call to ServiceMock.GetWallet at\n%s", m.funcGetWalletOrigin)
	}

	if !m.GetWalletMock.invocationsDone() && afterGetWalletCounter > 0 {
		m.t.Errorf("Expected %d calls to ServiceMock.GetWallet at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetWalletMock.expectedInvocations), m.GetWalletMock.expectedInvocationsOrigin, afterGetWalletCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetWalletInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetWalletDone()
}
